<a href="https://colab.research.google.com/github/Kusumitha-1/ml-workshop/blob/main/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

**NumPy Array collection**

In [ ]:
list=[1,2,3,4,5]
array=np.array(list)
print(array)

[1 2 3 4 5]


In [ ]:
arr=np.array([2,3,45,45])
print(arr)

[ 2  3 45 45]


**Create 2-D Numpy Array**

In [ ]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


create 3-d array

In [9]:
arr3=np.array([[[1,2,3],[2,4,5],[3,4,5]],
              [[1,2,3],[23,3,4],[5,6,7]] ])
print(arr3)

print(arr3.size)
print(arr3.nbytes)


[[[ 1  2  3]
  [ 2  4  5]
  [ 3  4  5]]

 [[ 1  2  3]
  [23  3  4]
  [ 5  6  7]]]
18
144


check datatype of numpy array

In [ ]:
arr=np.array(["a","b"])
print(arr.dtype)

<U1


dimensions

In [ ]:
print(arr3.ndim)

3


shape attribute

In [ ]:
print(arr3.shape)

(2, 3, 3)


itemsize attribute

In [ ]:
arr2=np.array([1,2,3],dtype=np.int32)
print(arr2.itemsize)
print(arr3.itemsize)

4
8


data attribute

In [ ]:
print("data of arr2",arr2.data)
#prints memory adresss

data of arr2 <memory at 0x7b62b4d4f280>


access arrya elements using index

In [ ]:
print(array[2])
print(array[-1])

3
5


statistical

In [4]:
arr=np.array([1,2,3,4,5])
mean_arr=np.mean(arr)
median_arr=np.median(arr)
std_arr=np.std(arr)
print(mean_arr)
print(median_arr)
print(std_arr)

3.0
3.0
1.4142135623730951


In [8]:
 marks=np.array([90,80,70,60])
 print(np.percentile(marks,80))
 print(np.max(marks))
 print(np.min(marks))
 print(marks.nbytes)

84.0
90
60
32
